server:
  port: 8081
spring:
  datasource:
    url:  jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform:  org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled:  true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
  health:
    ratelimiters:
      enabled: true

resilience4j:
  ratelimiter:
    instances:
      address-service:
        limit-for-period: 1
        limit-refresh-period: 15s
        timeout-duration: 10s
        register-health-indicator: true

